services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  CounterBundle\Command\:
    resource: '../../Command/'
  CounterBundle\Controller\:
    resource: '../../Controller/'
  CounterBundle\EventSubscriber\:
    resource: '../../EventSubscriber/'
  CounterBundle\Provider\:
    resource: '../../Provider/'
  CounterBundle\Repository\:
    resource: '../../Repository/'
  CounterBundle\Service\:
    resource: '../../Service/'
